import { build } from 'esbuild';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

// Compile one shared validator into the browser bundle. Function.toString()
// is unsafe here: Worker bundling can inject helper references into functions.
const result = await build({
  entryPoints: [fileURLToPath(new URL('../src/mkv-review-client.js', import.meta.url))],
  bundle: true, platform: 'browser', format: 'iife', target: 'es2022',
  write: false, minify: true, legalComments: 'none',
});
const script = result.outputFiles[0].text;
if (/<\/script/i.test(script)) throw new Error('Unsafe embedded script terminator');
await writeFile(new URL('../src/mkv-review-client.generated.js', import.meta.url),
  '// Generated by scripts/build-review.mjs; do not edit.\nexport default ' + JSON.stringify(script) + ';\n');
