import assert from 'node:assert/strict';
import { cachedGpuPipeline } from '../renderers/shared/gpu-pipeline-cache.js';
import { PALETTES, buildPaletteLut, getPaletteLut } from '../renderers/shared/palettes.js';
let lose;
const device = {lost: new Promise(resolve => { lose = resolve; })};
let compiled = 0;
const compile = () => ({id: ++compiled});
const [a,b] = await Promise.all([cachedGpuPipeline(device,'image',compile),cachedGpuPipeline(device,'image',compile)]);
assert.equal(a,b); assert.equal(compiled,1);
await assert.rejects(cachedGpuPipeline(device,'failed',()=>{throw new Error('driver rejected');}));
assert.equal((await cachedGpuPipeline(device,'failed',compile)).id,2);
lose(); await device.lost;
assert.notEqual(await cachedGpuPipeline(device,'image',compile),a);
const first = getPaletteLut(PALETTES[0].id);
assert.equal(getPaletteLut(PALETTES[0].id),first);
assert.deepEqual(first,buildPaletteLut(PALETTES[0].id));
for(const palette of PALETTES) getPaletteLut(palette.id);
assert.notEqual(getPaletteLut(PALETTES[0].id),first, 'cache evicts old entries');
console.log('GPU compilation coalescing, failed/device-lost retry and bounded palette cache passed');
